# Generated by Django 4.0.3 on 2022-04-10 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('descriptioin', models.TextField(null=True)),
                ('link', models.CharField(max_length=2000)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
